package webServiceResources;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-02-28T17:29:11.706+03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://www.example.org/InternationalTime/", name = "InternationalTime")
@XmlSeeAlso({ObjectFactory.class})
public interface InternationalTime {

    @WebMethod(action = "http://www.example.org/InternationalTime/getInternationaTime")
    @RequestWrapper(localName = "getInternationaTime", targetNamespace = "http://www.example.org/InternationalTime/", className = "webServiceResources.Location")
    @ResponseWrapper(localName = "getInternationaTimeResponse", targetNamespace = "http://www.example.org/InternationalTime/", className = "webServiceResources.GetInternationaTimeResponse")
    @WebResult(name = "out", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar getInternationaTime(

        @WebParam(name = "Country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "City", targetNamespace = "")
        java.lang.String city
    ) throws DatatypeConfigurationException;
}
