package webServiceResources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-02-28T17:29:11.847+03:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "InternationalTime",
                  wsdlLocation = "file:/C:/Users/Bob/eclipse-workspace/webservices/topDownApproach/src/main/resources/InternationalTime.wsdl",
                  targetNamespace = "http://www.example.org/InternationalTime/")
public class InternationalTime_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/InternationalTime/", "InternationalTime");
    public final static QName InternationalTimeSOAP = new QName("http://www.example.org/InternationalTime/", "InternationalTimeSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Bob/eclipse-workspace/webservices/topDownApproach/src/main/resources/InternationalTime.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InternationalTime_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Bob/eclipse-workspace/webservices/topDownApproach/src/main/resources/InternationalTime.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InternationalTime_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InternationalTime_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InternationalTime_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InternationalTime_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InternationalTime_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InternationalTime_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InternationalTime
     */
    @WebEndpoint(name = "InternationalTimeSOAP")
    public InternationalTime getInternationalTimeSOAP() {
        return super.getPort(InternationalTimeSOAP, InternationalTime.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InternationalTime
     */
    @WebEndpoint(name = "InternationalTimeSOAP")
    public InternationalTime getInternationalTimeSOAP(WebServiceFeature... features) {
        return super.getPort(InternationalTimeSOAP, InternationalTime.class, features);
    }

}
